---
- name: "updadte apt packages"
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes


- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Executing node
  shell: |
    git clone https://github.com/engbaher77/cdond-c3-projectstarter.git
    cd cdond-c3-projectstarter
    cd backend
    npm i
    npm run build
    # cd ..
    # cp backend ./circleci/ansible/roles/deploy/files
    # cd ./circleci/ansible/roles/deploy/files
    ls


- name: Executing node
  shell: |
    ls
    # cd ~/web
    cd cdond-c3-projectstarter/backend
    pm2 stop default
    pm2 start npm -- start


# npm install
# pm2 stop default
# pm2 start npm -- start