Parameters:
  # New Bucket name
  MyBucketName:
    Description: Existing Bucket name
    Type: String

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${MyBucketName}"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'WebsiteBucket'
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]


# command: |
#             aws cloudformation deploy \
#             --template-file bucket.yml \
#             --stack-name stack-create-bucket-${CIRCLE_WORKFLOW_ID:0:7} \
#             --parameter-overrides MyBucketName="mybucket-${CIRCLE_WORKFLOW_ID:0:7}"


#aws cloudformation deploy --template-file .\cloudFormation\bucket.yml --stack-name stack-create-bucket-udapeople-kk1j287dhjppmz437123876 --parameter-overrides MyBucketName="udapeople-kk1j287dhjppmz437123876" --profile udacity1 --region us-east-1